global:
  scrape_interval: 5s
  external_labels:
    monitor: ubuntu

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [10.1.30.91:9090]

  - job_name: node-exporter
    static_configs:
      - targets: [10.1.30.91:9100]

  - job_name: loki
    static_configs:
      - targets: [10.1.30.91:3100]

  - job_name: promtail
    static_configs:
    - targets: [10.1.30.91:9080]

  - job_name: cadvisor
    static_configs:
    - targets:
      - cadvisor:8080